name: Notify on Workflow Failure

on:
  workflow_run:
    workflows: ["*"] # This listens to all workflows
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": "**:x: Workflow Failure Detected on Main Branch**",
              "embeds": [
                {
                  "title": "Workflow: '${{ github.event.workflow_run.name }}'",
                  "description": "The workflow **${{ github.event.workflow_run.name }}** has failed on the main branch.",
                  "url": "${{ github.event.workflow_run.html_url }}",
                  "color": 15158332
                }
              ]
            }' \
            $DISCORD_WEBHOOK_URL
